name: posekit
dependencies:
  - python=3.7.11
  - pip=21.2.2
  - cudatoolkit=11.3
  - conda-forge::ezc3d=1.1.1
  - pytorch::pytorch=1.10.0
  - pytorch::torchvision=0.11.1
  - swig=4.0.2
  - conda-forge::glfw=3.3
  - scipy=1.4.1
  - cmake=3.14.0
  - pytest=5.2.0
  - pytest-mock=1.11.2
  - hypothesis=4.44.2
  - toolz=0.10.0
  - pip:
    - phx-class-registry==3.0.5
    - tvl-backends-nvdec==0.1.0b18
    - glfw==1.8.3
    - PyOpenGL==3.1.5
    - PyOpenGL-accelerate==3.1.5
